### ISSUE TITLE
[Bug]:  Not compatible with tiptap editor

### ISSUE THREAD

**Issue by DevRaeph** [GuavaCZ/filament-knowledge-base#11]
### What happened?

If you try to use it along with tiptap editor you can't install it.

`
  Problem 1
    - guava/filament-knowledge-base[1.0.0, ..., 1.1.5] require spatie/shiki-php ^2.0 -> found spatie/shiki-php[2.0.0] but it conflicts with your root composer.json require (^1.3).
    - Root composer.json requires guava/filament-knowledge-base * -> satisfiable by guava/filament-knowledge-base[1.0.0, ..., 1.1.5].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require guava/filament-knowledge-base:*" to figure out if any version is installable, or "composer require guava/filament-knowledge-base:^2.1" if you know which you need.
`

### How to reproduce the bug

Is it possible to change the spatie/shiki-php package to version 1.3 instead of ^2.0?
I guess this would solve the  bug.

### Package Version

newest

### PHP Version

8.3

### Laravel Version

11.6

### Which operating systems does with happen with?

macOS

**Comment by gavinhewitt** [comment]
@lukas-frey This was the plugin that needed to be removed in order to be able to install KB. I think I also needed to remove Curator (both by AWCodes).

**Comment by DevRaeph** [comment]
Sadly, the "ueberdosis/tiptap-php" repo seems abandoned. This is used by AWCodes for the TipTap Editor.

**Comment by lukas-frey** [comment]
I'm honestly not sure what difference there is between version 1.3 and 2.0, I'll need to check and see if I can support both of the versions.

Alternatively I can add shiki-php as an optional dependency, since you need to opt-in for the functionality anyways (because of the additional installation steps).

**Comment by DevRaeph** [comment]
it seems there isn't a bis difference between these two packages. 

`The getAvailableLanguages, getAvailableThemes, languageIsAvailable and themeIsAvailable methods have been removed. These are no longer necessary as Shiki 1.0 lazy loads these when necessary.`

**Comment by DevRaeph** [comment]
i'll check if i can accomplish a backwards compatibility :)

**Comment by lukas-frey** [comment]
> i'll check if i can accomplish a backwards compatibility :)

That would be neat! :)

For now, version 1.2.0 has `spatie/shiki-php` only as a suggested package and if you want to use syntax highlighting, you need to manually install it.

**Comment by lukas-frey** [comment]
> I've tried it now, and i got i working without any problems.
> 
> ![image](https://private-user-images.githubusercontent.com/58560217/328533282-181bf0a2-e3a5-4450-a149-7e32ce273614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTA0MzcsIm5iZiI6MTcxNTA5MDEzNywicGF0aCI6Ii81ODU2MDIxNy8zMjg1MzMyODItMTgxYmYwYTItZTNhNS00NDUwLWExNDktN2UzMmNlMjczNjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzNTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZGQ5NmUyZDJiYTI4MTk5YTUzZTU3MGE0NmUxYzllNGMzOWM0NzMwYjMxM2M2NzEzYzBjZDg5YjkxNDA0NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gCJcgZW25YM6fjb-nN9ypC3kikBhDzwk-I-ybLCxoq4)
> 
> I've just changed your composer.json to `"spatie/shiki-php": "^1.3",` and the package.json to `"shiki": "^0.10.0",`. if you run npm i shiki@0.10.0 it worked without any problems.

Okay, I did not change the JS version of the package, but we need to make sure it works with both 1.3 and 2.0.

> The only thing i encouted, thats my problem i guess, i needed to add `'/Users/myuser/Library/Application Support/Herd/config/nvm/versions/node/v21.7.3/bin'` to the getLanguage function in FencedCodeRenderer.php on line 35.
> 
> i guess thats a problem with herd :D

That's not a problem with Herd (I mean it kinda is), but the solution is different, I linked it in the documentation: https://github.com/spatie/shiki-php?tab=readme-ov-file#using-node-version-manager

You should symlink your nvm node to the place where it would normally be if you installed it locally.

**Comment by DevRaeph** [comment]
yeah i think both will work.
Just apply the little hint in the docs with the other Versions and i think this will be good to go :)

**Comment by lukas-frey** [comment]
> yeah i think both will work. Just apply the little hint in the docs with the other Versions and i think this will be good to go :)

You are right, spatie/shiki-php 1.x works with shiki 0.x and spatie/shiki-php 2.x works with shiki 1.x.

I still like keeping it opt-in due to the installation steps that are present anyways, I'll add the info about the different versions then.

Thanks a lot for looking into it Raphael!

**Comment by DevRaeph** [comment]
No Problem, please adapt also the "syntaxHighlighting" funciton where you check for the installed version.
Thanks for the effort and keep it up :)

**Comment by lukas-frey** [comment]
Done in 1.2.1
