### ISSUE TITLE
[Request]: Move Documentation Link to Profile Menu

### ISSUE THREAD

**Issue by iAmKevinMcKee** [GuavaCZ/filament-knowledge-base#14]
### What happened?

Not a bug, but I would prefer to not have the Documentation link at the bottom of the sidebar. I think it's more intuitive and less obtrusive to have it in the Header Menu Items, like this:
![image](https://github.com/GuavaCZ/filament-knowledge-base/assets/4503765/647d2a94-651c-461d-8d86-73b622736e5d)

I've just added it there manually, but it would be great if there was a way to configure the plugin to either be there or in the sidebar.

Even if you don't give users the option to choose where it goes, it would be nice to be able to disable the sidebar link so you can manually put the link wherever you want.

### How to reproduce the bug

N/A

### Package Version

1.2.1

### PHP Version

8.2

### Laravel Version

10

**Comment by lukas-frey** [comment]
Good idea, thank you for the suggestion, Kevin! I'll add some way to customize it and/or disable it :)

**Comment by gavinhewitt** [comment]
Personally I would like to be able to add it to a navigationgroup, but I'm not sure how that would/could work :-)

**Comment by lukas-frey** [comment]
Yeah, I'm sure a lot of people will have their own unique place for it :D 

But since it would require a different style for each place, I think the best would be to add an option to disable it completely and then you can add your own render hooks and place it whereever you want.

**Comment by gavinhewitt** [comment]
> But since it would require a different style for each place, I think the best would be to add an option to disable it completely and then you can add your own render hooks and place it whereever you want.

That would be my preferred option :-)

**Comment by lukas-frey** [comment]
From version 1.3.0 onward it's now possible to disable the knowledge base panel button in order to use custom render hooks.

There is also a new back to default panel button which can also be disabled.
