### ISSUE TITLE
[Request]: Add discussions to github

### ISSUE THREAD

**Issue by gavinhewitt** [GuavaCZ/filament-knowledge-base#15]
### What happened?

You now have to open a bug report to ask a question or request a feature. I'm not too familiar with all GH settings but it looks like discussions need to be enabled somewhere, and linked correctly in `config.yml`.

### How to reproduce the bug

Not a bug

### Package Version

latest

### PHP Version

latest

### Laravel Version

latest

**Comment by gavinhewitt** [comment]
It's not really necessary, but it feels a bit weird to use a bug report. Also you have to fill in these fields that are not applicable. But it's not a biggie.

I agree that discussions sometimes get lost a bit :-)

**Comment by lukas-frey** [comment]
I think I should be able to add a Feature Request template among the regular Bug Issues.
