### ISSUE TITLE
[Request]: Add a class to the documentation content div

### ISSUE THREAD

**Issue by gavinhewitt** [GuavaCZ/filament-knowledge-base#16]
### What happened?

I would like to request to have a class/hook added to the documentation div so it can be targeted. For instance, I'd like to use Tailwind's `prose` class to format text, but the only option now is to target`fi-page`, which affects all parts of the page.

It's the div that starts with
```php
<div x-data
    x-init="
let anchors = document.querySelectorAll('.gu-kb-anchor');
...
```

### How to reproduce the bug

Yes

### Package Version

latest

### PHP Version

latest

### Laravel Version

latest

**Comment by lukas-frey** [comment]
Good point, I'll add it. I'm not sure how the prose class works under the hood though and I'm afraid it will get overwritten by the classes that the package adds itself.

I honestly didn't know there was anything like the prose class in tailwind, could have saved me from trying to style it manually. :D

**Comment by gavinhewitt** [comment]
> Good point, I'll add it. I'm not sure how the prose class works under the hood though and I'm afraid it will get overwritten by the classes that the package adds itself.

I added in the vendor package as a test and it looks good.
 
> I honestly didn't know there was anything like the prose class in tailwind, could have saved me from trying to style it manually. :D
:-D
 
> Maybe it's worth considering using it as a default.
It would require users to have the tailwind typography plugin installed. Other than that it's a great default.

**Comment by lukas-frey** [comment]
Yes, but isn't typography a prerequisite already for Filament anyways?

I know that when installing Filament Forms separetely, you need to install tailwind typography: https://filamentphp.com/docs/3.x/forms/installation#installing-tailwind-css

So I guess it's the same for Panels.

**Comment by gavinhewitt** [comment]
> Yes, but isn't typography a prerequisite already for Filament anyways?
> 
> I know that when installing Filament Forms separetely, you need to install tailwind typography: https://filamentphp.com/docs/3.x/forms/installation#installing-tailwind-css
> 
> So I guess it's the same for Panels.

I commented without checking so you're probably right ;-)

**Comment by gavinhewitt** [comment]
> I added in the vendor package as a test and it looks good.

Not entirely true. At first glance it looks ok but actually the markdown extensions are in the way which results in spacings etc to be incorrect :-(

**Comment by lukas-frey** [comment]
> > I added in the vendor package as a test and it looks good.
> 
> Not entirely true. At first glance it looks ok but actually the markdown extensions are in the way which results in spacings etc to be incorrect :-(

Yeah, but by default there wouldn't be any styling, I added those. So if using prose by default (I'll have to try tomorrow) works, I'll just remove all styling except for the more specific blocks such as Markers and Code blocks maybe (because I add a copy to clipboard button and the Language Name to it)

**Comment by gavinhewitt** [comment]
What it looks like with the classes disabled:

![image](https://github.com/GuavaCZ/filament-knowledge-base/assets/1969103/90b56c50-5dc6-46c9-bce1-53b4cce902b3)

**Comment by iAmKevinMcKee** [comment]
Prose can be nice, but I also find the width of the standard prose class to be too narrow. I would typically want to use something like `prose prose-2xl` or something like that. So would be great if the plugin can allow you to add classes directly.

Also would be good to set a manual class so if someone wants to write standard CSS to target the doc body, they can do that as well.

**Comment by lukas-frey** [comment]
Good points, I'll be adding "empty" gu-kb- classes everywhere so people can override these themselves.

And also, I'm probably going to need some help with moving to prose. I've temporarily removed all my stylings from the markdown and added the `prose` class, but the resulting content looks like this:
<img width="546" alt="image" src="https://github.com/GuavaCZ/filament-knowledge-base/assets/10926334/ef2c2455-a220-4f63-8fe0-f935930d0438">

Which doesn't look good tbh. The big gap between h1 and h2 shouldn't be there, as mentioned in their live demo.

**Comment by gavinhewitt** [comment]
> Which doesn't look good tbh. The big gap between h1 and h2 shouldn't be there, as mentioned in their live demo.

Which demo is that? I'm looking at https://tailwindcss-typography.vercel.app/ but there's no stacked H1 H2 there. I see a gap here too but maybe that's how it's supposed to be?

![image](https://github.com/GuavaCZ/filament-knowledge-base/assets/1969103/f4f45aa5-d28c-4800-876b-6228e3ab603a)

**Comment by gavinhewitt** [comment]
> > Which doesn't look good tbh. The big gap between h1 and h2 shouldn't be there, as mentioned in their live demo.
> 
> Which demo is that? I'm looking at https://tailwindcss-typography.vercel.app/ but there's no stacked H1 H2 there. I see a gap locally too but maybe that's how it's supposed to be?
> 
> ![image](https://private-user-images.githubusercontent.com/1969103/329033038-f4f45aa5-d28c-4800-876b-6228e3ab603a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTkzNjAsIm5iZiI6MTcxNTE5OTA2MCwicGF0aCI6Ii8xOTY5MTAzLzMyOTAzMzAzOC1mNGY0NWFhNS1kMjhjLTQ4MDAtODc2Yi02MjI4ZTNhYjYwM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMjAxMTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI3N2Y1MmZhM2M3MjFmYmNkMGQxOGM5ZDc1NWQ0ZGM5NGJhOTMwZGJkZjlhOTNiMWE2ODExZDI5NjEyZTJlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o1PDnXNVs80_oxwEjiiORPDBcSvGvZFe84CF8o0dB5k)

**Comment by gavinhewitt** [comment]
Demo on Tailwind play:

<img width="958" alt="image" src="https://github.com/GuavaCZ/filament-knowledge-base/assets/1969103/1da9f795-3b26-4ec5-809f-33d4a0a6dae9">

Looks like the gap is supposed to be ike that

**Comment by lukas-frey** [comment]
> Demo on Tailwind play (https://play.tailwindcss.com/umBcTQU2x3?layout=preview):
> 
> 
> 
> <img width="958" alt="image" src="https://github.com/GuavaCZ/filament-knowledge-base/assets/1969103/1da9f795-3b26-4ec5-809f-33d4a0a6dae9">
> 
> 
> 
> 
> 
> Looks like the gap is supposed to be like that

![image](https://github.com/GuavaCZ/filament-knowledge-base/assets/10926334/cb291349-0b04-403c-9854-9c7507970fcb)

The top margin wasn't removed, but maybe it's because I stacked three headings 🤔

**Comment by lukas-frey** [comment]
In version 1.3.0 there is a `gu-kb-article` class on the main article div. Also you can add custom classes using:
```php
use Guava\FilamentKnowledgeBase\Filament\Panels\KnowledgeBasePanel;

KnowledgeBasePanel::configureUsing(
    fn(KnowledgeBasePanel $panel) => $panel
        ->articleClass('max-w-2xl')
);
```
