### ISSUE TITLE
[Request]: Add right sidebar even when there's no headings in the content

### ISSUE THREAD

**Issue by gavinhewitt** [GuavaCZ/filament-knowledge-base#17]
### What happened?

Depending on if there's H's in the content there's a sidebar that shows the links to the sections, which is great ux. However, when there's no headings the sidebar is removed which makes the content full width, which is ugly. I would like to see that the content section always stays the same width.

You could set it yourself if a hook class is added to the content (https://github.com/GuavaCZ/filament-knowledge-base/issues/16#issue-2284374361), but I think it should be the default.

### How to reproduce the bug

Yes

### Package Version

latest

### PHP Version

latest

### Laravel Version

latest

**Comment by lukas-frey** [comment]
Hehe, I was wondering how long it'll take until someone notices it :D 

I don't like it either, it's just I use sub-record navigation which hides by default when there's nothing in it.

Would you prefer if the content was then centered? Not sure how I feel about leaving white space on the right instead of the sub record navigation.

**Comment by gavinhewitt** [comment]
> Would you prefer if the content was then centered? Not sure how I feel about leaving white space on the right instead of the sub record navigation.

Centering would mean that the layout changes inconsistently. One way to overcome this is to make the content div a fixed width?

**Comment by lukas-frey** [comment]
I need to set this issue aside for now. I don't like using tailwind's `prose` class until I find out why it's not working as it should. The margins it sets are different than from the live demo.

Also having the sidebar there always is something I'm not totally liking. However there's going to be an option to add classes and a `gu-kb-article` class or something that you can use to set your own preferred max width if you like.

**Comment by gavinhewitt** [comment]
> Also having the sidebar there always is something I'm not totally liking. However there's going to be an option to add classes and a `gu-kb-article` class or something that you can use to set your own preferred max width if you like.

Having a class to target already solves it! 👍🏼

**Comment by lukas-frey** [comment]
In version 1.3.0 there is an option to disable the right sidebar. There is also a `gu-kb-article` class that you can target on the documentation article. Check docs for more info :)
