### ISSUE TITLE
[Bug]: On smaller screens the anchor (#) on headings partly falls of the screen

### ISSUE THREAD

**Issue by gavinhewitt** [GuavaCZ/filament-knowledge-base#18]
### What happened?

See title

### How to reproduce the bug

X

### Package Version

latest

### PHP Version

latest

### Laravel Version

latest

**Comment by lukas-frey** [comment]
Oops, good catch. I'll try to work through all the issues tomorrow :-)

**Comment by gavinhewitt** [comment]
> Oops, good catch. I'll try to work through all the issues tomorrow :-)

Personally not a fan of those markers. I think they should be, again, optional :-D

**Comment by lukas-frey** [comment]
> > Oops, good catch. I'll try to work through all the issues tomorrow :-)
> 
> Personally not a fan of those markers. I think they should be, again, optional :-D

Why optional though? Just don't use them if you don't like them and they will never appear anywhere? :D

**Comment by gavinhewitt** [comment]
Sorry my bad, I meant the anchors that are automatically added to headings :-) (#)

**Comment by lukas-frey** [comment]
Oooh, you mean that! So you're suggesting to keep the table of contents on the right, but disable the anchors on the left? 🤔 

Would you prefer if it appeared only on hover though? That was also a possibility I was considering :D

**Comment by gavinhewitt** [comment]
> Oooh, you mean that! So you're suggesting to keep the table of contents on the right, but disable the anchors on the left? 🤔

Yes

> Would you prefer if it appeared only on hover though? That was also a possibility I was considering :D
That would be one possibility yes. But I wouldn't miss them if they were gone completely :-)

**Comment by lukas-frey** [comment]
Yeah, I'm thinking adding some "empty" `gu-kb-` classes everywhere just like filament does, so you can style most stuff however you see fit, add a disable option and maybe one or two presets you can choose from (the way it is now + maybe the hovering version).

**Comment by lukas-frey** [comment]
Fixed in 1.3.0. Works on smaller screens and can be disabled entirely.

**Comment by gavinhewitt** [comment]
Thanks Lukas, you rock!
