### ISSUE TITLE
[Feature]: Option to disable the default Markdown attributes

### ISSUE THREAD

**Issue by gavinhewitt** [GuavaCZ/filament-knowledge-base#19]
### What happened?

Haha sorry, me again ;-)

Thank you for adding the option to set classes for the article! However, the default attributes now mess with the appearance. I have added `prose`, but (for instance) headings are off because they are overruled by the defaults. Of course I can target them in my custom css, but that kind of defeats the purpose of the option to set your own classes.

I would like to propose that no defaults are being set if any custom classes are present, or something like that.

Sorry for keeping you busy ;)

### How to reproduce the bug

See title

### Package Version

latest

### PHP Version

latest

### Laravel Version

latest

**Comment by lukas-frey** [comment]
The issue is that this then collides with all other defaults like the Code Syntax Highlighting. I have added Alpine stuff, such as the copy to clipboard action, that I would need to remove also in that case.

**Comment by gavinhewitt** [comment]
Does the Alpine stuff also target styling or is it only the class name thats used? (diving in to source now)

**Comment by lukas-frey** [comment]
I wrap it inside a container and I apply the styling on the container. The inner `code` block is render via shiki. But the tailwind prose thingy targets the code blocks, so it adds margins inside the code block, wheares I add the margins on the container, since the container adds that header with the language name and the action.

**Comment by lukas-frey** [comment]
> Hmm I see.
> 
> But to disable defaults for H, P, TABLE and BLOCKQUOTE only is not an option?

It is, but then you'll have a huge margin inside the code block. Because the prose class will add it inside the container.

**Comment by gavinhewitt** [comment]
> > Hmm I see.
> > But to disable defaults for H, P, TABLE and BLOCKQUOTE only is not an option?
> 
> It is, but then you'll have a huge margin inside the code block. Because the prose class will add it inside the container.

Personally I don't have a use for code blocks (yet) so I'm not really bothered by that. But I can imagine others are.

I'd say I'd rather then target the code block specifically to remove something when using prose, instead of having to target multiple elements just to add or overrule something :)

**Comment by gavinhewitt** [comment]
> Well in that case I'll add a `disableDefaultClasses` or something similar to the KB panel. :)

Well, what if you put the classes in the config? That way you don't have to disable anything. People can just remove stuff there.

**Comment by lukas-frey** [comment]
> > Well in that case I'll add a `disableDefaultClasses` or something similar to the KB panel. :)
> 
> Well, what if you put the classes in the config? That way you don't have to disable anything. People can just remove stuff there.

That would add yet another directory you need to add to your Vite Theme that would check for Tailwind Classes. I'm already unhappy with having to go through both `resources` and `src` :D

**Comment by gavinhewitt** [comment]
Ah, valid point!

`disableDefaultClasses()` would be a better choice then :)

**Comment by lukas-frey** [comment]
Added in version 1.4.0. :)

**Comment by gavinhewitt** [comment]
> Added in version 1.4.0. :)

Perfect, thanks! 💪🏽

But you know I'm gonna come back with more, right? 😅

**Comment by lukas-frey** [comment]
Lol, I'm already looking forward to it :-)
