### ISSUE TITLE
[Request]: Option to add custom Commonmark extensions

### ISSUE THREAD

**Issue by gavinhewitt** [GuavaCZ/filament-knowledge-base#20]
### What happened?

See title

### How to reproduce the bug

See title

### Package Version

latest

### PHP Version

latest

### Laravel Version

latest

**Comment by lukas-frey** [comment]
Hello Gavin.

In the latest release I added a new extension and with that I streamlined the visibility of the methods.

You were able to use your own implementation of the `MarkdownRenderer` anyways, so I removed the final modifier of the class. You can now just extend it, override the `customizeEnvironment` to register your new extensions and then bind your new `MarkdownRenderer` to the app container.

This way you can now add any new extensions you like.
