### ISSUE TITLE
[Bug]: CSS Not Applied to Help Action Modal

### ISSUE THREAD

**Issue by iAmKevinMcKee** [GuavaCZ/filament-knowledge-base#22]
### What happened?

When using the HelpAction on a form component, I can include content from my docs but it is not styled the same as in my documentation panel.

### How to reproduce the bug

Use a HelpAction with a hintAction on a form component

### Package Version

latest

### PHP Version

latest

### Laravel Version

latest

### Notes

For me, I'm overriding custom styles and just targeting the `.gu-kb-article` class in a CSS file, so I would just need this class applied to the modal.

However, I'm not sure about other implementations.

**Comment by lukas-frey** [comment]
Fixed in version 1.4.1. 

Due to a refactor, please make sure to now run `php artisan filament:assets`, so that the alpine components get installed in your project. :)
