### ISSUE TITLE
[Request]: Turn off Single Page Application mode

### ISSUE THREAD

**Issue by iAmKevinMcKee** [GuavaCZ/filament-knowledge-base#23]
### What feature would you like to add?

Right now spa mode is on by default, and I don't see any way to turn it off. I've tried

```php
 KnowledgeBasePanel::configureUsing(
            fn (KnowledgeBasePanel $panel) => $panel->spa(false));
```

But that doesn't work.

The problem when one panel has spa mode and others don't, you get weird behavior when going back and forth. When going from the knowledge base to another panel without spa mode on, the first time you navigate to the other panel, the global search is still the KB search until there is another page refresh.

**Comment by lukas-frey** [comment]
Fixed in #24
