### ISSUE TITLE
[Request]: The knowledge base panel needs to be registered with a custom vite theme.

### ISSUE THREAD

**Issue by dmb-220** [GuavaCZ/filament-knowledge-base#25]
### What feature would you like to add?

The knowledge base panel needs to be registered with a custom vite theme. new install laraavel new versio 11.10 new filament 3.2.85 press documentation button get error

**Comment by dmb-220** [comment]
http://new.test/kb//prologue/getting-started get Not Found

The requested URL was not found on this server.

**Comment by cooljet84** [comment]
You should configure the custom theme in you AppServiceProvider (app/Providers/AppServiceProvider.php)
not in your Panel ServiceProvider

```
use Guava\FilamentKnowledgeBase\Filament\Panels\KnowledgeBasePanel;
 
KnowledgeBasePanel::configureUsing(
    fn(KnowledgeBasePanel $panel) => $panel
        ->viteTheme('resources/css/filament/admin/theme.css') // your filament vite theme path here
);
```

**Comment by damms005** [comment]
@dmb-220 I can almost bet that you are registering this in your `boot()` method like every other Filament setup plugin.
The docs, unusual of most filament plugins, instructs that it should be registered `in the register method`.

I have a good number of filament plugins in my app, and this is the first and only plugin that registerd in `register` method of service provider. @cooljet84 any ideas why this design decision please?

**Comment by eelco2k** [comment]
@cooljet84 i've got the same problem. i've added the configureUsing() function to my AppServiceProvider.php

but i still get the error that i need to use custom theme.

```php
 KnowledgeBasePanel::configureUsing(function (KnowledgeBasePanel $panel) {
            return
                $panel
                    ->brandName('Knowledge base')
                    ->guestAccess(true)
                    ->disableBackToDefaultPanelButton()
                    // ->syntaxHighlighting() // Needs nodeJs on server
                    ->viteTheme('resources/css/filament/portal/theme.css')
                    ->middleware([
                        'requestlog',
                    ]);
            }
```
i'm using the same custom viteTheme as in my Portal filament admin panel.

I've also run the `npm run build` and double checked the manual as stated here: https://filamentphp.com/docs/3.x/panels/themes#creating-a-custom-theme

**Comment by eelco2k** [comment]
Also when i set breakpoints with XDebug.
```php
 KnowledgeBasePanel::configureUsing(function (KnowledgeBasePanel $panel) {
            $test = $panel ; // added breakpoint here.... 
```
the debugger does not execute the function in ::configureUsing... so it looks like it's not correctly registered...

**Comment by agruenberg** [comment]
@damms005 You saved my evening ;)

**Comment by OlyaK95** [comment]
Can somebody help me?

I placed this code in `AppServiceProvider.php`
![2024-07-28_15-49-32](https://github.com/user-attachments/assets/ff322695-e447-40fc-9c35-5b9f594d5ea6)

And I can open my Knowledge Base
![2024-07-28_15-51-33](https://github.com/user-attachments/assets/81c2f09b-0e69-44df-ae7b-4ce8833bba41)

But I have 404 error
![2024-07-28_15-52-08](https://github.com/user-attachments/assets/f0cb460a-299d-4c53-aebd-d3c012d2d885)

**Comment by OlyaK95** [comment]
@lukas-frey I think I need your help..

**Comment by eelco2k** [comment]
@OlyaK95 I don’t understand why your url get encoded with \ also visible in your address bar with: %5C

\ are for namespaces, not paths in url. Not sure it is related to that. Just wild guessing

**Comment by OlyaK95** [comment]
> @OlyaK95 I don’t understand why your url get encoded with \ also visible in your address bar with: %5C
> 
> \ are for namespaces, not paths in url. Not sure it is related to that. Just wild guessing

I tried manually change path to `http://filament.test/kb\prologue\getting-started` and to `http://filament.test/kb/prologue/getting-started`
Nothing changes... 404

**Comment by eelco2k** [comment]
What do the PHP artisan route:list say for the kb urls?

**Comment by OlyaK95** [comment]
> What do the PHP artisan route:list say for the kb urls?

Routes about `kb`

 ```
 GET|HEAD   kb ............................................................................................................................................................................................................................. filament.knowledge-base.pages.dashboard › Filament\Pages › Dashboard  
  POST       kb/logout .................................................................................................................................................................................................................... filament.knowledge-base.auth.logout › Filament\Http › LogoutController  
  GET|HEAD   kb/{record?} ................................................................................................................................................................................ filament.knowledge-base.resources.documentations.view › Guava\FilamentKnowledgeBase › ViewDocumentation
```

**Comment by eelco2k** [comment]
and your config ?

**Comment by OlyaK95** [comment]
> and your config ?

default
```php
<?php

// config for Guava/KnowledgeBasePanel
return [
    "panel" => [
        "id" => env("FILAMENT_KB_ID", "knowledge-base"),
        "path" => env("FILAMENT_KB_PATH", "kb"),
    ],

    "docs-path" => env("FILAMENT_KB_DOCS_PATH", "docs"),

    "model" => \Guava\FilamentKnowledgeBase\Models\FlatfileDocumentation::class,

    "cache" => [
        "prefix" => env("FILAMENT_KB_CACHE_PREFIX", "filament_kb_"),
        "ttl" => env("FILAMENT_KB_CACHE_TTL", "forever"),
    ],
];
```

**Comment by eelco2k** [comment]
you're caching infinite so try to clear cache `php artisan cache:clear`  and the docs folder in is your root project folder with 

docs (folder)
  -> en (folder)
     -> proloque (folder)
        getting-started.md (file)

**Comment by OlyaK95** [comment]
> you're caching infinite so try to clear cache `php artisan cache:clear` and the docs folder in is your root project folder with
> 
> docs (folder) -> en (folder) -> proloque (folder) getting-started.md (file)
> 
> ![Scherm­afbeelding 2024-07-28 om 18 43 47](https://private-user-images.githubusercontent.com/878103/352853964-4ef617fd-21db-49b6-aa0f-351f52ca69b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODU1MzgsIm5iZiI6MTcyMjE4NTIzOCwicGF0aCI6Ii84NzgxMDMvMzUyODUzOTY0LTRlZjYxN2ZkLTIxZGItNDliNi1hYTBmLTM1MWY1MmNhNjliOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxNjQ3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmIyMzM3ZmI3NDllMDRjMjZlOWUxM2Q0OWU2MDNiZTc4MjUwZTU0MzBkM2QzOTQ2MjU1MGUwNTNiMzhlNDgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BmvrUQ4sW6XxqcO67CAvy2wjjLWJNDStXnceOZoETMI)

I did `php artisan optimize:clear`
I also tried delete Chrome cache
Then I deleted my `docs/ru` directory and recreated it

Now I have error
![image](https://github.com/user-attachments/assets/1ab4ad33-1120-41f6-8d5c-e48e6ccfbc4e)

**Comment by eelco2k** [comment]
And I assume you also registered the plugin in you PanelProvider of you filament panel? as otherwise it would not show up in routes list.
```php
->plugins( [KnowledgeBasePlugin::make() ])

If this does not work i'm also out of options as here v1.9.0 it works, with same config (except for the "forever")

**Comment by OlyaK95** [comment]
> And I assume you also registered the plugin in you PanelProvider of you filament panel? as otherwise it would not show up in routes list.
> 
> ```
> ->plugins( [KnowledgeBasePlugin::make() ])
> 
> If this does not work i'm also out of options as here v1.9.0 it works, with same config (except for the "forever")
> ```

Of course
![2024-07-28_19-49-38](https://github.com/user-attachments/assets/94d1edf7-0bdb-4c26-9a84-ea18f8bc2331)

**Comment by eelco2k** [comment]
i see that the FlatfileDocumentation class uses Sushi package which uses by default an sqlite db (which is just a binary file in the project)  it tries to insert the data into this sqlite file but the syntax is incorrect. So you haven't edited the the vendor/guava/filament-knowledge-base/ files? 

to be sure: remove this folder, and run composer install again. it will redownload the whole package. furthermore you are sure you don't use any special characters in the  *.md files?

**Comment by eelco2k** [comment]
also make sure sushi works correctly and it meets your requirements:
https://github.com/calebporzio/sushi

**Comment by eelco2k** [comment]
sqlite file should be in folder : storage/framework/cache/sushi-xxxxxx.sqlite

**Comment by eelco2k** [comment]
as written in de readme of sushi, if it cant create an sqlite file it will use in-memory. you'll then have to check whether there are any .env requirements needed for that or that it just works out of the box (the fallback)

**Comment by OlyaK95** [comment]
> i see that the FlatfileDocumentation class uses Sushi package which uses by default an sqlite db (which is just a binary file in the project) it tries to insert the data into this sqlite file but the syntax is incorrect. So you haven't edited the the vendor/guava/filament-knowledge-base/ files?
> 
> perhaps also remove calebporzio/sushi from vendor folder.
> 
> to be sure: remove this folder, and run composer install again. it will redownload the whole package. furthermore you are sure you don't use any special characters in the *.md files?

No, I don't edit any files in this folder.

I did it, reinstall packag

**Comment by OlyaK95** [comment]
> sqlite file should be in folder : storage/framework/cache/sushi-xxxxxx.sqlite

I have no file sqlite(

**Comment by eelco2k** [comment]
I think you have to debug further. as normally it should work. try dd() instead of the return statement of the FlatfileDocumentation.php Models file  in the public function getRows()
{

return collect(.....)->toArray();

change temporary to:

dd(collect(....)->toArray());

**Comment by OlyaK95** [comment]
@eelco2k I got this

![2024-07-28_20-31-52](https://github.com/user-attachments/assets/873128f5-9fd8-4583-ab75-64d292dd4579)

**Comment by eelco2k** [comment]
I think i know the issue: it's in windows right? as the path is D:\ 

it uses all \ instead of / 

those will not get replaced...

i think because \SplFileInfo $file works in windows differently...

some sort of ->replace('\\', '/') has to be added

**Comment by eelco2k** [comment]
So not related to the package.... but i would suggest run the laravel project in laravel sail with WSL. you'll have linux containers for php etc. and you don't have the issue i bet

**Comment by OlyaK95** [comment]
> I think i know the issue: it's in windows right? as the path is D:\
> 
> it uses all \ instead of /
> 
> those will not get replaced...
> 
> i think because \SplFileInfo $file works in windows differently...
> 
> some sort of
> 
> ```
>  ->replace('\\', '/')
> ```
> 
> has to be added

You are right, it is Windows OS.

**Comment by OlyaK95** [comment]
> So not fully related to the package.... but GuavaCZ could do some find and replace...
> 
> for now i would suggest run the laravel project in laravel sail with WSL. you'll have linux containers for php etc. and you don't have the issue i bet

I am so grateful to you, thank you. I will wait GuavaCZ answer now.

**Comment by lukas-frey** [comment]
Yeah, sorry, I will have to recheck all the classes and fix the path separators for all OSes. Thanks for the info.

@eelco2k Not sure if you fixed your issue, but as @damms005 suggested, the part where you configure your knowledge base panel (`KnowledgeBasePanel::configureUsing(...)`) has to be done in the `register` method, not in the `boot` method.

This is because Filament registers all panels in the `register` phase. If you run it during `boot`, the panel will already be registered and all your customisations will not be applied by then yet.

**Comment by eelco2k** [comment]
@lukas-frey Yes fixed it 👍
