### ISSUE TITLE
[Request]: Table of content ordering

### ISSUE THREAD

**Issue by damms005** [GuavaCZ/filament-knowledge-base#26]
### What feature would you like to add?

Just like the items can be ordered from the dropdown, allow ordering of items on the TOC using same ordering maybe?

**Comment by lukas-frey** [comment]
Hi @damms005 I'm not sure what you mean by that. If you're referring to the Table of Contents on the right side of each documentation page: That is sorted automatically based on the headings in the content of your markdown file.

**Comment by iAmKevinMcKee** [comment]
I think he means on the left sidebar. Right now, the top level directories are sorted alphabetically. It would be nice to be able to choose the order here. I think it goes along with #21 where there may need to be a config or something to be able to control some of these things.

**Comment by lukas-frey** [comment]
In the md file of the documentation, you can add `order` into the front matter.

**Comment by damms005** [comment]
This `order` option in the front matter that you mentioned above is not documented, do you want to do that?

**Comment by damms005** [comment]
I just tried it and it is exactly the feature I wanted. Maybe docment it? (the front matter `order` option).

Thanks! 😄

**Comment by lukas-frey** [comment]
> This `order` option in the front matter that you mentioned above is not documented, do you want to do that?

Yeah, I need to add it to the documentation. There's more things I forgot to mention probably :D
