### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ainesophaur** [GuavaCZ/filament-knowledge-base#28]
### What happened?

I've noticed a warning in my console after adding this package package 

> uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in ...Collection.php on line 1412

I narrowed it down to the sorting logic in [KnowledgeBasePanel.php#L243](https://github.com/GuavaCZ/filament-knowledge-base/blob/42d82613bddb675ac753d3ea3189c6fe20b4e22e/src/Filament/Panels/KnowledgeBasePanel.php#L243) and [KnowledgeBasePanel.php#L279](https://github.com/GuavaCZ/filament-knowledge-base/blob/42d82613bddb675ac753d3ea3189c6fe20b4e22e/src/Filament/Panels/KnowledgeBasePanel.php#L279) returning booleans instead of the expected sorting values of -1,0 or 1.

Changing the comparison to the [spaceship operator](https://www.php.net/manual/en/language.operators.comparison.php) resolves this issue 

```php
->sort(fn (Documentable $d1, Documentable $d2) => $d1->getOrder() <=> $d2->getOrder())
```

I would be happy to open a PR if desired.

### How to reproduce the bug

Nothing special should be required

### Package Version

1.6.0

### PHP Version

8.3.8

### Laravel Version

11.11.0

**Comment by lukas-frey** [comment]
Hi Travis, thanks for the report! I'll gladly accept a PR. :)
