### ISSUE TITLE
[Bug]: flatfile_documentations create table issue

### ISSUE THREAD

**Issue by markwillow** [GuavaCZ/filament-knowledge-base#40]
### What happened?

It happens after I install the plugin to my filament.

"php": "^8.1",
        "blade-ui-kit/blade-icons": "^1.5",
        "doctrine/dbal": "^3.7",
        "eightynine/filament-excel-import": "^3.0",
        "filament/filament": "^3.2-stable",
        "guava/filament-knowledge-base": "^1.9",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/horizon": "^5.22",
        "laravel/octane": "^2.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "livewire/livewire": "^3.0@beta",
        "pxlrbt/filament-excel": "^2.3",
        "sentry/sentry-laravel": "^3.6",
        "spatie/laravel-activitylog": "^4.7",
        "spatie/laravel-data": "^3.6",
        "spatie/laravel-google-cloud-storage": "^2.3",
        "spatie/laravel-permission": "^5.10",
        "tapp/filament-timezone-field": "^3.0"

### How to reproduce the bug

It happens after I install the plugin to my filament.

Illuminate
 \ 
Database
 \ 
QueryException
PHP 8.2.12
10.48.18
SQLSTATE[HY000]: General error: 1 near ")": syntax error
CREATE TABLE "flatfile_documentations" ()

<?php $layout->viewContext->mergeIntoNewEnvironment($__env); ?>

    @component($layout->view, $layout->params)

        @slot($layout->slotOrSection)

            {!! $content !!}

        @endslot

        <?php

        // Manually forward slots defined in the Livewire template into the layout component...

        foreach ($layout->viewContext->slots[-1] ?? [] as $name => $slot) {

            $__env->slot($name, attributes: $slot->attributes->getAttributes());

            echo $slot->toHtml();

            $__env->endSlot();

        }

        ?>

    @endcomponent

### Package Version

 1.9.2

### PHP Version

8.1

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS

**Comment by markwillow** [comment]
I just resolved the issue by modifying the actual vendor file by adding a  protected $schema function .

`
<?php

namespace Guava\FilamentKnowledgeBase\Models;

use Arr;
use Filament\Navigation\NavigationGroup;
use Guava\FilamentKnowledgeBase\Contracts\Documentable;
use Guava\FilamentKnowledgeBase\Facades\KnowledgeBase;
use Guava\FilamentKnowledgeBase\Filament\Pages\ViewDocumentation;
use Guava\FilamentKnowledgeBase\Markdown\MarkdownRenderer;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use League\CommonMark\Extension\FrontMatter\Output\RenderedContentWithFrontMatter;
use League\CommonMark\Extension\HeadingPermalink\HeadingPermalink;
use League\CommonMark\Output\RenderedContentInterface;
use Sushi\Sushi;

class FlatfileDocumentation extends Model implements Documentable
{
    use Sushi;

    public $incrementing = false;

    protected $schema = [
        'id' => 'string',
        'slug' => 'string',
        'path' => 'string',
        'content' => 'text',
        'title' => 'string',
        'group' => 'string',
        'icon' => 'string',
        'parent' => 'string',
        'order' => 'integer',
    ];

    public function getRows()
    {
        $path = base_path(
            str(config('filament-knowledge-base.docs-path'))
                ->append('/')
                ->append(App::getLocale())
        );

        return collect(File::allFiles($path))
            ->map(function (\SplFileInfo $file) use ($path) {
                $data = KnowledgeBase::parseMarkdown($file->getRealPath());

                $id = str($file->getPathname())
                    ->afterLast($path)
                    ->beforeLast($file->getExtension())
                    ->replace(DIRECTORY_SEPARATOR, '.')
                    ->trim('.')
                ;

                $parts = $id->explode('.', 3);
                $group = data_get($data, 'front-matter.group');
                $parent = data_get($data, 'front-matter.parent');
                if (count($parts) >= 2) {
                    $group ??= Str::headline($parts[0]);
                }
                if (count($parts) >= 3) {
                    $parent ??= Str::headline($parts[1]);
                }

                return [
                    'id' => $id,
                    'slug' => $id->replace('.', '/')->toString(),
                    'path' => $file->getRealPath(),
                    'content' => data_get($data, 'html'),
                    'title' => data_get($data, 'front-matter.title', $id->afterLast('.')->headline()),
                    'group' => $group,
                    'icon' => data_get($data, 'front-matter.icon'),
                    'parent' => $parent,
                    'order' => data_get($data, 'front-matter.order'),
                ];
            })
            ->toArray()
            ;
    }

    public function getFrontMatter(): array
    {
        $result = $this->getHtml();

        if ($result instanceof RenderedContentWithFrontMatter) {
            return $result->getFrontMatter();
        }

        return [];
    }

    public function getHtml(): RenderedContentInterface
    {
        $converter = app(MarkdownRenderer::class);

        return $converter->convert(file_get_contents($this->path));
    }

    public function getSimpleHtml(): RenderedContentInterface
    {
        $converter = app(MarkdownRenderer::class)->minimal();

        return $converter->convert(file_get_contents($this->path));
    }

    public function getUrl(): string
    {
        return ViewDocumentation::getUrl(parameters: [
            'record' => $this,
        ], panel: KnowledgeBase::panelId());
    }

    public function getAnchors()
    {
        $walker = $this->getHtml()->getDocument()->walker();
        $anchors = [];
        while ($event = $walker->next()) {
            $node = $event->getNode();

            if ($event->isEntering() && $node instanceof HeadingPermalink) {
                $slug = $node->getSlug();
                $next = $node->next();
                if (! method_exists($next, 'getLiteral')) {
                    continue;
                }
                $anchors[$next->getLiteral()] = $slug;
            }
        }

        return $anchors;
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getContent(): string
    {
        return $this->content;
    }

    public function getParent(): ?string
    {
        return $this->parent;
    }

    public function getParentId(): ?string
    {
        $parts = str($this->getId())->explode('.', 3);
        if (count($parts) >= 3) {
            return $parts[0] . '.' . $parts[1];
        }

        return null;
    }

    public function getGroup(): ?string
    {
        return $this->group;
    }

    public function getOrder(): int
    {
        return $this->order ?? 0;
    }

    public function getIcon(): ?string
    {
        return $this->icon ?? 'heroicon-o-document';
    }

    public function isRegistered(): bool
    {
        return ! empty($this->getTitle());
    }

    public function getBreadcrumbs(): array
    {
        return collect([
            KnowledgeBase::panel()->getUrl() => __('filament-knowledge-base::translations.knowledge-base'),
        ])
            ->when(
                $group = $this->getGroup(),
                fn (Collection $collection) => $collection->put($this->getGroupUrl() . '#', $group)
            )
            ->when(
                $parent = $this->getParent(),
                fn (Collection $collection) => $collection->put(
                    KnowledgeBase::documentable($this->getParentId())->getUrl(),
                    $parent,
                )
            )
            ->put($this->getUrl(), $this->getTitle())
            ->toArray()
            ;
    }

    public function getGroupUrl()
    {
        $group = collect(KnowledgeBase::panel()->getNavigation())
            ->first(function ($item) {
                return $item instanceof NavigationGroup && $item->getLabel() === $this->getGroup();
            })
        ;

        if ($group) {
            return Arr::first($group->getItems())->getUrl();
        }

        return null;
    }
}
`

**Comment by lukas-frey** [comment]
Thanks for the info. I haven't tested it with L10, maybe Laravel of Sushi behaves differently there, since it seems to work in L11 without the schema array.

I'll check and add it if necessary in the next release.

**Comment by markwillow** [comment]
Thanks.

**Comment by mrvnklm** [comment]
> Thanks for the info. I haven't tested it with L10, maybe Laravel or Sushi behaves differently there, since it seems to work in L11 without the schema array.
> 
> I'll check and add it if necessary in the next release.

I get the same error on fresh install with laravel 11
