### ISSUE TITLE
[Request]: Side Bar Guide

### ISSUE THREAD

**Issue by markwillow** [GuavaCZ/filament-knowledge-base#42]
### What feature would you like to add?

Hi Developers. I tried looking for the left side bar guide however, I can't find it anywhere.

**Comment by lukas-frey** [comment]
Hi, I'm not sure what you mean.

The left sidebar (panel navigation) is created automatically from all your docs. The right sidebar is the table of contents, which is created also automatically based on the headings from your markdown file.

**Comment by markwillow** [comment]
Hi Lukas.

I am referring to this:

![image](https://github.com/user-attachments/assets/54421e2e-19bd-4069-920b-fd01eabb68bf)

**Comment by lukas-frey** [comment]
Ah, I see. I've described it in the issue here https://github.com/GuavaCZ/filament-knowledge-base/issues/30#issuecomment-2194223523 

I need to add some more info in the docs about the front matter.

**Comment by lukas-frey** [comment]
I've added some info to the readme about the different front matter options.

**Comment by markwillow** [comment]
To clarify the process of creating a parent-child relationship in the left-side navigation panel, please follow these steps:

1. **Create a parent document**: Execute the command `docs:make test.main`.
2. **Update your data**: Ensure to set the title, for instance, `title: Main`.
3. **Create a child document**: Execute the command `docs:make test.child1`.
4. **Update your data**: Add a title and specify the parent. For example, `parent: Main`. Note that this is case-sensitive, so ensure the data matches precisely.

**Comment by CharlieEtienne** [comment]
Hi,

When I follow the steps given by @markwillow , I get an error:

```
Guava\FilamentKnowledgeBase\KnowledgeBase::documentable(): Argument #1 ($documentable) must be of type
Guava\FilamentKnowledgeBase\Contracts\Documentable|string, null given, called in /Users/charlie/Herd/test-
filament/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 358
```

My files:

```
/docs/fr/test/main.md
/docs/fr/test/child1.md
```

**/docs/fr/test/main.md**

```markdown
---
title: Main
---

# Main

Lorem ipsum dolor sit amet
```

**/docs/fr/test/child1.md**

```markdown
---
title: Child 1
parent: Main
---

# Child 1

Lorem ipsum dolor sit amet
```
