### ISSUE TITLE
[Request]: Only Embedded Documentation (Disable Dedicated Panel)

### ISSUE THREAD

**Issue by lorenzoaiello** [GuavaCZ/filament-knowledge-base#52]
### What feature would you like to add?

I'm using this plugin to render documentation within my admin panel, but do not necessarily want the docs panel enabled. It would be great if there was a way to simply disable it altogether without losing the rest of the plugin's functionality.

**Comment by lukas-frey** [comment]
You can however forbid access to the panel using the `canAccessPanel` method of your User model. Just return false for the Knowledge Base panel.
