### ISSUE TITLE
[Bug]: Auth guard [web] is not defined.

### ISSUE THREAD

**Issue by MaartenJC** [GuavaCZ/filament-knowledge-base#61]
### What happened?

After installation of this plugin the Filament page gives an error:
Auth guard [web] is not defined.

### How to reproduce the bug

i do not use the default guard 'web' but a custom frontend and backend guard.

### Package Version

1.10.1

### PHP Version

8.2.23

### Laravel Version

10.48.22

### Which operating systems does with happen with?

macOS

**Comment by lukas-frey** [comment]
Override the `authGuard` on the knowledge base panel:
https://github.com/GuavaCZ/filament-knowledge-base?tab=readme-ov-file#customize-the-knowledge-base-panel

**Comment by MaartenJC** [comment]
Thanks for your response.
This is now in my AppServiceProvider:

```
KnowledgeBasePanel::configureUsing(
            fn (KnowledgeBasePanel $panel) => $panel
                ->authGuard('frontend')
                ->viteTheme('resources/css/filament/admin/theme.css') // your filament vite theme path here
        );
```
Still the same error.

**Comment by MaartenJC** [comment]
I was calling it from the boot method, changed it to the register method. Now it works!
Thanks for your support. Looks like a great plugin!

**Comment by lukas-frey** [comment]
Thanks! Glad I could help.
