### ISSUE TITLE
[Bug]: SQLSTATE[HY000]: General error: 1 near ")": syntax error (Connection: , SQL: create table "flatfile_documentations" ())

### ISSUE THREAD

**Issue by AxelvdS** [GuavaCZ/filament-knowledge-base#63]
### What happened?

I have installed the package with success on my Mac in development and have an issue similar to [M40](https://github.com/GuavaCZ/filament-knowledge-base/issues/40 ). The error is: SQLSTATE[HY000]: General error: 1 near ")": syntax error (Connection: , SQL: create table "flatfile_documentations" ())

### How to reproduce the bug

I have tried to create a new install and it has the same issue.
It is fixed after adding the schema:
``
  
  	protected $schema = [
      'id' => 'string',
      'slug' => 'string',
      'path' => 'string',
      'content' => 'text',
      'title' => 'string',
      'group' => 'string',
      'icon' => 'string',
      'parent' => 'string',
      'order' => 'integer',
    ]
``

### Package Version

1.10

### PHP Version

8.3.12

### Laravel Version

11.28.1

### Which operating systems does with happen with?

Linux

### Notes

It seems that the database (MariaDB for Linux and MySQL for MacOs) is the key difference.

**Comment by AxelvdS** [comment]
The file edited is: vendors\guava/filament-knowledge-bases/src/Models/FlatfileDocumentation.src

**Comment by lukas-frey** [comment]
Thanks for the headsup! Seems like Sushi throws this error when the dataset is empty (you haven't created any documentations yet) and adding the `$schema` manually fixes it.

Fixed in 1.10.3

**Comment by AxelvdS** [comment]
Thanks!Regards, AxelOn 26 Oct 2024, at 10:01 PM, Lukas Frey ***@***.***> wrote:﻿
Thanks for the headsup! Seems like Sushi throws this error when the dataset is empty (you haven't created any documentations yet) and adding the $schema manually fixes it.
Fixed in 1.10.3
